# Generated by Django 4.0.1 on 2022-03-20 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('tag', models.AutoField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
                ('weight', models.FloatField()),
                ('years', models.CharField(blank=True, max_length=200, null=True)),
                ('diseases', models.CharField(blank=True, max_length=1000, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=200, null=True)),
                ('referred', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('treatment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.treatment')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.animal')),
            ],
        ),
    ]
