# Generated by Django 4.0.3 on 2022-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='clientType',
            field=models.CharField(default='Farmer', max_length=200),
        ),
    ]
