# Generated by Django 4.0.3 on 2022-03-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
