# Generated by Django 4.0.3 on 2022-03-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_disease_id_alter_symptoms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
