# Generated by Django 4.0.3 on 2022-03-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_symptoms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='book',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='book',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
