# Generated by Django 4.0.3 on 2022-04-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sales_date_sales_description_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorphone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
